### ISSUE TITLE
linux系统中要求调用winreg模块

### ISSUE THREAD

**Issue by fatinghenji** [Nana-Miko/ChatLearning#1]
![image](https://user-images.githubusercontent.com/37131177/155196773-738b01f5-ae5d-41bb-bd29-0c9685e28be8.png)
我不知道咋整了

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/155196838-4cef95e3-3e17-42a2-8edb-e2c7e596e7cc.png)
补充报错截图

**Comment by FuYon** [comment]
应该直接装就行了，去整个miniconda配置python环境

**Comment by Nana-Miko** [comment]
重新下载最新版本就可以了
