### ISSUE TITLE
启动后提示 ： TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by kj863257** [Nana-Miko/ChatLearning#11]
如下：

```
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "ChatLearning.py", line 195, in main
  File "ChatLearning.py", line 156, in listening
  File "ChatLearning.py", line 123, in extractmessage
  File "simuse.py", line 68, in Fetch_Message
TypeError: 'int' object is not subscriptable
```

**Comment by Nana-Miko** [comment]
能让我看一下你的data.json文件吗？还有就是运行环境是linux还是windows？

**Comment by kj863257** [comment]
![image](https://user-images.githubusercontent.com/15863805/155464944-080d7188-802d-45ba-a57b-02eaba7ca8c5.png)
 
windows 运行环境

**Comment by Nana-Miko** [comment]
host改为127.0.0.1:8080
这个是我的问题，我在编写mirai-api-http统一接口的时候不小心把host+port整合了，下个版本会优化一下，感谢反馈

**Comment by kj863257** [comment]
原来如此，以为是文档描述的不对，写的是host 结果是 host+port  (笑哭)

**Comment by Nana-Miko** [comment]
历史遗留问题）一直懒得没修复，新版本会把他修上
今天下午新版本就会发布了

**Comment by kj863257** [comment]
还有个问题，执行参数的时候，如果写了多个空格会 ‘参数错误’

比如 `add replay  1234567`

这个是不是应该按 \s+ 分隔

**Comment by FuYon** [comment]
(slightly...)

**Comment by Nana-Miko** [comment]
确定你输入的是reply而不是replay嘛

**Comment by kj863257** [comment]
![image](https://user-images.githubusercontent.com/15863805/155469089-c1ded939-6ac8-4b56-b61e-e15fcab0e2a2.png)

**Comment by Nana-Miko** [comment]
这个确实是我的问题，在识别指令的时候没用上正则匹配）

**Comment by kj863257** [comment]
![image](https://user-images.githubusercontent.com/15863805/155469698-53f18161-9f6b-4442-8908-e1d6bd68dcd1.png)
这个又是什么情况

**Comment by Nana-Miko** [comment]
这个问题刚刚mirai论坛中的那位也遇到了，已经知道哪里出错了
目前解决方法是再重启一下learning指令
将会下次更新中修复

**Comment by Nana-Miko** [comment]
新版本已发布
