### ISSUE TITLE
【优化+拓展】近日版本更新用grouplist代替check

### ISSUE THREAD

**Issue by FuYon** [Nana-Miko/ChatLearning#12]
查询后bot返回的消息格式大概长这样：
这是我目前想到的关于信息这块最友好的方式，操作起来也很实用。
已开启记录和未开启记录的群给出问答信息就全面了
按照群人数排序

不是很建议使用转发模式，因为复制群号时需要频繁进出，可延时发送
![image](https://user-images.githubusercontent.com/57851695/155487653-05ea8db0-8e07-4694-b5f8-a95c1a6351ba.png)

**Comment by Nana-Miko** [comment]
很棒的建议，这样看起来确实直观多了
