### ISSUE TITLE
[A TOOL]将.cl文件转换成易读的txt文件

### ISSUE THREAD

**Issue by Nana-Miko** [Nana-Miko/ChatLearning#14]
目前正在制作一个工具，可将词库转换成txt文件，这样可以使用记事本或其他软件，从底层修改词库
![image](https://user-images.githubusercontent.com/46672817/155502760-bb43997b-aceb-4cad-82af-7eb341db163a.png)
转换效果图

**Comment by FuYon** [comment]
为什么要从底层修改词库呢，应该不是要去方便手工筛查一些词汇吧

**Comment by FuYon** [comment]
为什么要从底层修改词库呢，应该不是要去方便手工筛查一些词汇吧

**Comment by FuYon** [comment]
技术上虽然帮助不了，不过如果写出更多信息的话我可以提供思路上的帮助

**Comment by FuYon** [comment]
还有都这个点了就不要熬夜敲代码了

**Comment by Nana-Miko** [comment]
主要是没有一个比较好的方法，能列出一个群所有的问题列表，直接修改词库只是目前我能想到的一个比较能快速定位问题和答案，批量删除的一个手段

**Comment by FuYon** [comment]
这个可以有，但是我觉得优先级不高。是属于没辙了才会去做的下下签。先完善聊天环境下的查询和删除系统比较好。

还有，查询系统有个效率感觉不是很高但是也有优点的实现方法，就是把数据写入到某个云表格里，比如腾讯文档。

**Comment by FuYon** [comment]
![-51a08d014748b81b.png](https://user-images.githubusercontent.com/57851695/155550408-f54a37ee-0a51-4f87-a591-abe1fef7a8d4.png)
![Screenshot_20220224-230620_TIM.png](https://user-images.githubusercontent.com/57851695/155550434-50001d86-a954-46a0-9d5c-f3d2823207b2.png)

**Comment by FuYon** [comment]
话说咱加个qq会方便多了（）
1691914478

**Comment by Nana-Miko** [comment]
ok

**Comment by Nana-Miko** [comment]
> 

这个其实挺简单的，花了不到半个小时就搞定了，可以先作为临时解决手段，这种表格形式挺好的诶，我想想怎么做
