### ISSUE TITLE
Windows Server 2008不支持

### ISSUE THREAD

**Issue by hhhfsj** [Nana-Miko/ChatLearning#15]
`Error loading Python DLL 'C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI37202\python39.dll'.`

**Comment by Nana-Miko** [comment]
python 3.9不支持win7以下系统，可以尝试下载linux版本，然后用您的python运行Chatmain.py

**Comment by FuYon** [comment]
小白装Ubuntu就行，20网上自带3.8
