### ISSUE TITLE
细分全局词库种类

### ISSUE THREAD

**Issue by fatinghenji** [Nana-Miko/ChatLearning#16]
### 进行多个merge？
我现在的bot目标人群有三种：方舟玩家、FF玩家、~色图群~。每种人群都有多个群聊，而相同类型的群聊内容可以互通，比如：`FF1群`、`FF2群`、`明日方舟1群`、`明日方舟2群`、`色图1群`、`色图2群`。能否对不同的群体进行单独的merge，形成下面这样？
- mergeA：`FF1群`、`FF2群`
- mergeB：`明日方舟1群`、`明日方舟2群`
- mergeC：`色图1群`、`色图2群`
- mergeD：通用
### 将问题及答案标注有效时间？
这样就可以避免：
![image](https://user-images.githubusercontent.com/37131177/155929057-38a5c2f8-ec7c-41b5-b8b7-17a1e31065f0.png)

**Comment by Nana-Miko** [comment]
已收到您的建议
还有您是希望自动清理时间跨度大的问题和答案吗

**Comment by fatinghenji** [comment]
>还有您是希望自动清理时间跨度大的问题和答案吗
对啊对啊，游戏类随着时间的推移版本的迭代讨论内容会变化的，或者将远古答案的权重降低也可以。问题和答案的权重随着时间的推移而降低，当再次出现相同的问题的时候提高权重或将计时器归零重新计时？

**Comment by Nana-Miko** [comment]
我觉得可行，已列入计划
现在记录的词库是带有时间属性的，查找的时候就会给出来，现在最新版还支持全部查找和列出本群所有词库了，可以先用这个来删除一些比较久的词条

**Comment by fatinghenji** [comment]
~我又来提需求了~
在后面的版本是否可以支持对应群的群管理员(群主)来管理自己群的词库？
一个人管理过多的词库太累了(

**Comment by FuYon** [comment]
如果是仅赋予他们
查看/编辑 本群 词库的权限，我觉得ok

**Comment by fatinghenji** [comment]
> 如果是仅赋予他们 查看/编辑 本群 词库的权限，我觉得ok

对，就是让A群的管理员管理A群词库，查看不了B群词库这样

**Comment by Nana-Miko** [comment]
收到!不过这样有可能造成冲突，比如一个群的在操作，另外一个就操作不了

**Comment by FuYon** [comment]
先close掉节省空间，会放到todo里面

**Comment by Nana-Miko** [comment]
久等了，这个功能终于在2.8.0发布了
