### ISSUE TITLE
磁盘余量用光之后有写坏文件的 bug

### ISSUE THREAD

**Issue by SyuueenN** [Nana-Miko/ChatLearning#19]
磁盘满时程序依然收集问题并写入 .cl 文件，此时会发生文件损坏的情况。具体表现为控制台报错（忘记留下日志），文件 0 B，无法打开查看内容。正常的 .cl 文件如下图，是可以显示出内容的。腾出磁盘空间之后，将问题文件简单删除即复原，但结果而言在写坏的时刻就失去了一个文件之前为止的记录。希望修复相关的逻辑，谢谢！
![image](https://user-images.githubusercontent.com/42110156/156896720-3d034555-6311-4157-9b96-45307ad3c053.png)

**Comment by Nana-Miko** [comment]
了解，当时没有考虑到磁盘空间占满的问题

**Comment by FuYon** [comment]
额，我觉得倒是完全不必要，这种问题你应该升级自己的存储，那么小的文件都装不了才是大问题
