### ISSUE TITLE
管理员无法使用admin

### ISSUE THREAD

**Issue by fatinghenji** [Nana-Miko/ChatLearning#21]
解决方法：qq设置里手动关闭所有临时会话

---

暂时找到了问题的原因——腾讯将新加的好友在bot端判定为陌生人：
![image](https://user-images.githubusercontent.com/37131177/157078131-e67f25c8-29ea-4598-90d4-30f4dfc80dd6.png)
在这种情况下，mirai传递的消息链中所包含的身份信息为`Stranger`
~~解决办法：手动添加对方为好友（
能否在下一个版本中，允许身份为`Stranger`的受信用户来进行admin的操作呢？毕竟是手动添加到admin列表里面的。~~

**Comment by Nana-Miko** [comment]
试试重启一下ChatLearning，设置了管理员后需要重新启动

**Comment by Nana-Miko** [comment]
或者是因为刚加的好友，qq判定为临时消息而非私聊消息，可以试着先右滑删除聊天，从好友中向bot发起聊天

**Comment by fatinghenji** [comment]
两种方案都尝试了，依旧不行
不放心的跑去看了看`config.clc`，que're确认是有两位管理员的
![image](https://user-images.githubusercontent.com/37131177/156980183-ca71228f-e6d6-48e2-8b8f-b70d45baeae4.png)

**Comment by Nana-Miko** [comment]
了解，我今晚回去复现一下bug，然后修复一下

**Comment by Nana-Miko** [comment]
![HZRDT$B~UCVI{5`_7 QY{JR](https://user-images.githubusercontent.com/46672817/157021415-78726576-6e61-4d0f-bdde-013b5223778f.png)
![KH~9UMTLF@ZVS1$~VS@LW F](https://user-images.githubusercontent.com/46672817/157021466-02ccf7fc-e57c-4dd7-95ad-d68ba8e1b5c4.jpg)

我这边没法fu'xian复现您的BUG，请问是只有admin指令用不了吗？其他是否正常

**Comment by fatinghenji** [comment]
其他指令也无法使用，我又找了个群友进行测试，应该不是某一个qq号无法调用的问题。

**Comment by Nana-Miko** [comment]
其实也不是不可以开放这个权限，但是我不建议使用，这种会话会被视为临时消息，这是极其容易导致bot风控冻结的

**Comment by fatinghenji** [comment]
ok（

**Comment by fatinghenji** [comment]
刚说完bot就没了（
太草

**Comment by Nana-Miko** [comment]
> 刚说完bot就没了（ 太草

所以我建议把bot qq的允许临时会话关了）风险太大
