### ISSUE TITLE
请求新增权限及命令

### ISSUE THREAD

**Issue by fatinghenji** [Nana-Miko/ChatLearning#23]
### 新增superadmin权限
- superadmin所可以干的事情
  - 现在所有的命令
  - 通过`setadmin add *（QQ号）*（群号） `命令来添加相对应群的词库管理员
- admin可以干的事情
  - 管理本群的词库、回复频率、开关
 ### 新增`setadmin add *（QQ号）*（群号） `命令
- 现有的`setadmin` 命令在添加新的管理员时未明确是否会删除已存在的管理员
- 原因同上

**Comment by FuYon** [comment]
说复杂了。
1、admin群管可管理本群词库、开关。
2、添加管理员不会覆盖，单独增删。

**Comment by fatinghenji** [comment]
现在的admin权限还是看所有群（，将来会限制到仅看指定群聊吗？

**Comment by Nana-Miko** [comment]
> 现在的admin权限还是看所有群（，将来会限制到仅看指定群聊吗？

如果要做单独群的管理员那肯定是只能操作当前群的

**Comment by Nana-Miko** [comment]
> > > 现在的admin权限还是看所有群（，将来会限制到仅看指定群聊吗？
> > 
> > 
> > 如果要做单独群的管理员那肯定是只能操作当前群的
> 
> 有一个问题是，现在mirai支持读取当前群的群员列表及群主信息吗？如果支持的话就好办很多了，在开启reply和learning的同时，添加对应群聊的群管理为admin。免去手动添加的问题。

您好，新版本已支持该功能

**Comment by fatinghenji** [comment]
！好欸！
