### ISSUE TITLE
自动启动learning和reply

### ISSUE THREAD

**Issue by 4sh3z** [Nana-Miko/ChatLearning#26]
可不可以让ChatLearning在运行时就自动启动learning和reply。
还有退出admin模式时可不可以增加自动恢复learning和reply的开启呢，
每次退出admin模式之后要手动敲一遍!learning和!reply感觉有点麻烦。

**Comment by Nana-Miko** [comment]
> 可不可以让ChatLearning在运行时就自动启动learning和reply。 还有退出admin模式时可不可以增加自动恢复learning和reply的开启呢， 每次退出admin模式之后要手动敲一遍!learning和!reply感觉有点麻烦。

可以的，我下个版本把他做上吧

**Comment by 4sh3z** [comment]
辛苦你啦
