### ISSUE TITLE
隐私相关问题。希望有控制复读或收集类型的选项，特别是语音和闪照

### ISSUE THREAD

**Issue by SyuueenN** [Nana-Miko/ChatLearning#30]
简单说就是复读了别人的历史语音和闪照，有的还是已经撤回的，引发了恐慌。希望有选项能关闭收集发送这些……或其他类型的全部消息。

有关一般图片，因为一般的表情包和别人爆照性质的图片都会被收集、发出，也引发过一些恐慌。
个人看法是，这两者的区别一个是被大量重复、一个是昙花一现、很稀有。
所以希望能有一个根据重复次数多少决定是否发送的机制和选项。

**Comment by Nana-Miko** [comment]
那就不记录语音?然后图片类型的话重复一次以上才会被发送?

**Comment by SyuueenN** [comment]
> 那就不记录语音?然后图片类型的话重复一次以上才会被发送?

肯定还是有人喜欢复读语音或闪照这个功能的，所以最好提供个开关。
图片这样处理也好，不过还是希望不要写死。

**Comment by Nana-Miko** [comment]
> > 那就不记录语音?然后图片类型的话重复一次以上才会被发送?
> 
> 肯定还是有人喜欢复读语音或闪照这个功能的，所以最好提供个开关。
> 图片这样处理也好，不过还是希望不要写死。

好的，要写的话肯定不会写死的

**Comment by Nana-Miko** [comment]
见2.8.0更新

**Comment by SyuueenN** [comment]
> 见2.8.0更新

更新辛苦（鞠躬
