### ISSUE TITLE
请问是否支持过滤某个群员的问题&答案记录

### ISSUE THREAD

**Issue by sxjeru** [Nana-Miko/ChatLearning#31]
RT，有些人喜欢故意发 spam 消息，意图搞乱词库。
希望能自定义屏蔽一些qq号的发言 learning。

`最后感谢作者的项目贡献！`

**Comment by Nana-Miko** [comment]
> RT，有些人喜欢故意发 spam 消息，意图搞乱词库。
> 希望能自定义屏蔽一些qq号的发言 learning。
> 
> `最后感谢作者的项目贡献！`

是有这个功能的，在管理模式，过滤设置，添加黑名单

**Comment by sxjeru** [comment]
感谢回答。
