### ISSUE TITLE
功能建议：删除上一条发言记录

### ISSUE THREAD

**Issue by MokouTyan** [Nana-Miko/ChatLearning#35]
任意群友发送
！delete

1.删除该群里的最新一条问答
2.撤回机器人上一条内容（做不到这点也可以，最主要还是现在删除问答太麻烦了）

**Comment by MokouTyan** [comment]
3.机器人提示“删除成功”，然后过几秒撤回，或者是不提示删除成功也可以

**Comment by Nana-Miko** [comment]
已在计划内

**Comment by Nana-Miko** [comment]
确定任意群友都可执行该指令吗?

**Comment by MokouTyan** [comment]
> 确定任意群友都可执行该指令吗?

因为群友都知道那个账号是机器人，所以没必要只有管理员才能删记录，管理员也没有24小时在线
删除问答也不是很重要的事情，因为一般来说没有重要的问答

**Comment by Achley-233** [comment]
> 确定任意群友都可执行该指令吗?

也许让普通群友申请删除，然后bot发送给bot管理员申请信息？
bot管理员批准后再删除，同时向申请删除的普通群友发送申请通过的通知。

**Comment by MokouTyan** [comment]
> > 确定任意群友都可执行该指令吗?
> 
> 也许让普通群友申请删除，然后bot发送给bot管理员申请信息？ bot管理员批准后再删除，同时向申请删除的普通群友发送申请通过的通知。

太麻烦了，这个和用！admin来先查找后删除没什么两样

恶意删除也不会出事情，只是一条问答没了，现在网上建政的太多了，怕炸群了

恶意添加才会出事情

**Comment by Nana-Miko** [comment]
我还是选择权交给用户吧，自行设置管理员或者全员可执行该指令

**Comment by MokouTyan** [comment]
> 我还是选择权交给用户吧，自行设置管理员或者全员可执行该指令

删除最新那一条问答就行，一直往下删可能会出问题

在只有开启reply的群才能使用！delete

**Comment by Nana-Miko** [comment]
> > 我还是选择权交给用户吧，自行设置管理员或者全员可执行该指令
> 
> 删除最新那一条问答就行，一直往下删可能会出问题
> 
> 在只有开启reply的群才能使用！delete

就是在开启reply的群中才可使用
关于能删几条问答，我设置了一个缓存队列，自行设置容量，默认32。

**Comment by Nana-Miko** [comment]
> > 我还是选择权交给用户吧，自行设置管理员或者全员可执行该指令
> 
> 删除最新那一条问答就行，一直往下删可能会出问题
> 
> 在只有开启reply的群才能使用！delete

就是在开启reply的群中才可使用
关于能删几条问答，我设置了一个缓存队列，自行设置容量，默认32。

**Comment by MokouTyan** [comment]
> > > 我还是选择权交给用户吧，自行设置管理员或者全员可执行该指令
> > 
> > 
> > 删除最新那一条问答就行，一直往下删可能会出问题
> > 在只有开启reply的群才能使用！delete
> 
> 就是在开启reply的群中才可使用 关于能删几条问答，我设置了一个缓存队列，自行设置容量，默认32。

嗯，最好接到！delete指令后，立即发送删除成功这条消息

10秒后bot做：
撤回“删除成功”这条消息（影响版面）
尝试撤回群友的“！delete”消息
尝试撤回刚才bot发的问答（但是一般已经被群友撤回了
