### ISSUE TITLE
抛出异常

### ISSUE THREAD

**Issue by Elegantwolf** [Nana-Miko/ChatLearning#37]
抛出异常，已记录到日志(log.log文件)
Traceback (most recent call last):
  File "ChatClass.py", line 134, in run
  File "Chatmain.py", line 1418, in getcommand_chat
  File "simuse.py", line 83, in Fetch_Message
KeyError: 'data'

log:
2022-05-07 00:55:19
Traceback (most recent call last):
  File "ChatClass.py", line 134, in run
  File "Chatmain.py", line 1418, in getcommand_chat
  File "simuse.py", line 83, in Fetch_Message
KeyError: 'data'

Running MiraiConsole v2.10.1, built on 2022-03-08 21:54:56.
Frontend Terminal: version 2.10.1, provided by Mamoe Technologies
Plugins: net.mamoe.mirai-api-http v2.5.0, Chat Command v0.5.0, MCL Addon v2.0.2

Running on Centos7

data.json:
{
 "Key": "88xxxxx",
 "host": "127.0.0.1",
 "port": "5050",
 "qq": "21882xxxxxx",
 "session": "XXX"
}

setting.yml
singleMode: false
  http:
    host: 0.0.0.0
    port: 5050
    cors: ["*"]

**Comment by Elegantwolf** [comment]
问题出在mirai api http，mlc自带的2.5版本源存在问题，通过在mirai api http的release处下载解决了问题。

**Comment by JoyerLiu** [comment]
请问如何解决的，我也出现了这个问题，但是更换到2.3.3版本以及2.5.0版本均未解决这个问题

**Comment by Elegantwolf** [comment]
> 请问如何解决的，我也出现了这个问题，但是更换到2.3.3版本以及2.5.0版本均未解决这个问题

是mirai api http存在的问题，而不是mlc。可以去mirai api http的release中手动下载并安装。这条建议基于老旧版本，距今已经有近一年的时间，而且可能出现此类报错的原因应该不止一个。因此不能保证可以解决问题，只能作为解决问题的参考。

**Comment by JoyerLiu** [comment]
> > 请问如何解决的，我也出现了这个问题，但是更换到2.3.3版本以及2.5.0版本均未解决这个问题
> 
> 是mirai api http存在的问题，而不是mlc。可以去mirai api http的release中手动下载并安装。这条建议基于老旧版本，距今已经有近一年的时间，而且可能出现此类报错的原因应该不止一个。因此不能保证可以解决问题，只能作为解决问题的参考。

感谢，我去开一个Issues问问看
