### ISSUE TITLE
fastdelete的一些建议

### ISSUE THREAD

**Issue by MokouTyan** [Nana-Miko/ChatLearning#38]
这个功能非常实用，但是群友们不是很喜欢用，因此提出以下建议
》！delete缩短为！d
》尝试撤回发送删除指令的那条消息，手动撤回挺影响体验的（bot在群里一般也都会设为管理实现一些其他插件
》不用发送“删除成功”的结果了，删除失败再弹出删除失败的报错（也是影响版面的原因

**Comment by Nana-Miko** [comment]
删除成功会自动撤回，应该不太影响吧?给个提示会友好一点

**Comment by MokouTyan** [comment]
> 删除成功会自动撤回，应该不太影响吧?给个提示会友好一点

因为一般要撤回机器人的那条消息，和发送指令的在同一页，撤回成功的话很明显
或者说把“删除成功”改为“已从词库中删除”，有的群友容易误解成只有撤回，并不知道会从词库中删除

**Comment by Nana-Miko** [comment]
> > 删除成功会自动撤回，应该不太影响吧?给个提示会友好一点
> 
> 因为一般要撤回机器人的那条消息，和发送指令的在同一页，撤回成功的话很明显
> 或者说把“删除成功”改为“已从词库中删除”，有的群友容易误解成只有撤回，并不知道会从词库中删除

行!

**Comment by Nana-Miko** [comment]
2.9.5版本已更新相关内容

**Comment by angelina-9730** [comment]
快速删除的提示文本不妨也改成可以自定义？如果不想使用的话直接设为空之类的。这样会不会使用更友好一点

**Comment by Nana-Miko** [comment]
> 快速删除的提示文本不妨也改成可以自定义？如果不想使用的话直接设为空之类的。这样会不会使用更友好一点

可以

**Comment by Nana-Miko** [comment]
2.9.7已支持
