### ISSUE TITLE
有没有兴趣改一下或者加一下回复逻辑

### ISSUE THREAD

**Issue by jinxx52** [Nana-Miko/ChatLearning#39]
插件使用了很久，想提一下建议

增加一个回复模式

随机在几分钟内回复几率大幅增加

而不是每句单独的话有几率回复

现在十句里面蹦出来一句的样子还是有些诡异

这样子更像真人回复嘛
机器人水群的时代来临力

**Comment by Nana-Miko** [comment]
您的建议我收到了，目前正在开发可供用户自定义添加定时指令任务的功能，该功能应该可以实现您的提议

**Comment by jinxx52** [comment]
> 您的建议我收到了，目前正在开发可供用户自定义添加定时指令任务的功能，该功能应该可以实现您的提议

辛苦了！

**Comment by Nana-Miko** [comment]
请查看2.9.5版本的定时任务模块，可以实现你的需求

**Comment by jinxx52** [comment]
> 请查看2.9.5版本的定时任务模块，可以实现你的需求

芜湖 谢谢已经在用了
