### ISSUE TITLE
更新之后抛出异常TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by saltfish13** [Nana-Miko/ChatLearning#40]
![CWYP4Z ~2}M}JOJ@30LZTDH](https://user-images.githubusercontent.com/59356579/168483885-87deead3-86bd-4d76-b2f6-88a43b1a5d0c.png)
TypeError: 'int' object is not subscriptable

**Comment by Nana-Miko** [comment]
是从哪个版本更新上来的呢

**Comment by Nana-Miko** [comment]
替换exe后是会自动更新的，可能是第一次打开的时候未正常退出导致更新出错了

**Comment by saltfish13** [comment]
从1.0,2升上来的，多次打开还是抛出这个错误
