### ISSUE TITLE
ChatLearning控制台无法加载，可能是置于后台运行，或是程序退出

### ISSUE THREAD

**Issue by WeiYunfeng** [Nana-Miko/ChatLearning#41]
当mcl在screen后台运行时，显示：

ChatLearning控制台无法加载，可能是置于后台运行，或是程序退出

请问能否有持久化运行方法呢

**Comment by Nana-Miko** [comment]
在我的测试下，linux是可以用nohup &指令后台运行的，且输出也可正常重定向到nohup.out文件
