### ISSUE TITLE
通过指令输入Autotask任务记录 

### ISSUE THREAD

**Issue by angelina973** [Nana-Miko/ChatLearning#42]
autotask是个非常好用的功能，但是操作起来有些繁琐，尤其是当机器人架设在服务器上时。

可不可以将 autotask 加入终端命令（或许作为 admin 菜单的一个项目？）
通过直接在终端/聊天窗口输入任务语法来记录autotask信息，同时也可以将 autotask 和 admin 权限整合。

**Comment by angelina-9730** [comment]
> 好的，下次更新将交互性添加autotask写入admin中。autotask和admin权限整合请问是什么意思呢，是指autotask中可以使用admin?

就是说将管理 autotask 的功能整合进 admin 的菜单里啦

**Comment by Nana-Miko** [comment]
2.9.7已支持
