### ISSUE TITLE
文字转语音失败

### ISSUE THREAD

**Issue by PositionZer0** [Nana-Miko/ChatLearning#44]
在开启回复的群聊中发送 `@bot 快说 <文字>`，机器人没有反应，控制台输出“文字转语音失败”

系统是 Windows Server 2019，使用 ChatLearning.Source.zip 与 ChatLearning.Windows.zip 均有此问题

**Comment by Nana-Miko** [comment]
此前有没有使用uploadwav上传音源和setvoicept设置训练集？
请再仔细阅读一下readme

**Comment by PositionZer0** [comment]
> 此前有没有使用uploadwav上传音源和setvoicept设置训练集？ 请再仔细阅读一下readme

没有使用过`uploadwav`，只使用了`setvoicept <训练集名称>`。我用的是`setvoicept pretrained`

**Comment by Achley-233** [comment]
> > 此前有没有使用uploadwav上传音源和setvoicept设置训练集？ 请再仔细阅读一下readme
> 
> 没有使用过`uploadwav`，只使用了`setvoicept <训练集名称>`。我用的是`setvoicept pretrained`

需要先用`uploadwav`上传自己的音源捏
https://github.com/Nana-Miko/ChatLearning/blob/master/ToVoice/ToVoice.md#%E4%BD%BF%E7%94%A8%E6%AD%A5%E9%AA%A4

**Comment by PositionZer0** [comment]
> > > 此前有没有使用uploadwav上传音源和setvoicept设置训练集？ 请再仔细阅读一下readme
> > 
> > 
> > 没有使用过`uploadwav`，只使用了`setvoicept <训练集名称>`。我用的是`setvoicept pretrained`
> 
> 需要先用`uploadwav`上传自己的音源捏 https://github.com/Nana-Miko/ChatLearning/blob/master/ToVoice/ToVoice.md#%E4%BD%BF%E7%94%A8%E6%AD%A5%E9%AA%A4

明白了，感谢回复
