### ISSUE TITLE
[Performance] 优化流程，添加记录群号时默认配置回复群号

### ISSUE THREAD

**Issue by FuYon** [Nana-Miko/ChatLearning#5]
在绝大多数情况下，用户想要添加一个群的记录是因为想要在这个群启用回复。
所以在添加某群记录的时候同时默认此群开启回复即可。

**Comment by Nana-Miko** [comment]
好的，下次更新时将优化这一流程

**Comment by FuYon** [comment]
好的，我也正在学python，等我有能力了再pull request![WC@W5Q8R_G8{`KIHYXV6{RX](https://user-images.githubusercontent.com/57851695/155265820-96716f90-3388-47bc-a73c-e00254657f06.png)

**Comment by Nana-Miko** [comment]
其实我python也没学多久，有些代码结构其实不是很理想，add有些功能时会比较麻烦

**Comment by FuYon** [comment]
大大都学过哪些语言呀

**Comment by Nana-Miko** [comment]
python和C++
目前在学的有C# java还有一些前端语言
