### ISSUE TITLE
voicereply 无效

### ISSUE THREAD

**Issue by greenhandzdl** [Nana-Miko/ChatLearning#52]
![image](https://user-images.githubusercontent.com/61241103/181422904-3e7a0611-e398-4626-a566-4226ebf060d5.png)![image](https://user-images.githubusercontent.com/61241103/181422947-5bd0d8f1-abdc-40e6-8c00-74a0bd335376.png)

**Comment by greenhandzdl** [comment]
后面的指令直接无响应了，跟炸弹一样

**Comment by greenhandzdl** [comment]
重启中。。。
```
<function main at 0x3ffaa441820>：与api-http连接被强制中断
抛出异常，已记录到日志(log.log文件)
<function main at 0x3ffab22b940>：与api-http连接被强制中断
抛出异常，已记录到日志(log.log文件)
<function getcommand_chat at 0x3ffaa4bcca0>：与api-http连接被强制中断
抛出异常，已记录到日志(log.log文件)
Traceback (most recent call last):
  File "/home/linux1/mirai/ChatLearning V2.9.8/ChatClass.py", line 375, in run
    self._target(*self._args, **self._kwargs)
  File "/home/linux1/mirai/ChatLearning V2.9.8/ChatReply.py", line 624, in main
    listening(data)
  File "/home/linux1/mirai/ChatLearning V2.9.8/ChatReply.py", line 557, in listening
    message = simuse.Fetch_Message(data)  # 监听消息链
  File "/home/linux1/mirai/ChatLearning V2.9.8/simuse.py", line 89, in Fetch_Message
    Message = res['data']
KeyError: 'data'
```

**Comment by greenhandzdl** [comment]
![image](https://user-images.githubusercontent.com/61241103/181423787-ff136b3c-c76a-4c76-a087-56ad6c02be06.png)
我在想机器人是不是还存在概率回复

**Comment by Nana-Miko** [comment]
> ![image](https://user-images.githubusercontent.com/61241103/181423787-ff136b3c-c76a-4c76-a087-56ad6c02be06.png)
> 我在想机器人是不是还存在概率回复

你可以在你的本机测试一下有没有这个问题?我觉得是你的网络连接不够稳定，触发延迟了

**Comment by greenhandzdl** [comment]
可能不是网络不稳定这回事吧。。。
服务器网络挺好的。。。

**Comment by Nana-Miko** [comment]
> 可能不是网络不稳定这回事吧。。。
> 服务器网络挺好的。。。

试试本地运行?
