### ISSUE TITLE
手机QQ无法删除词库

### ISSUE THREAD

**Issue by MMM2042** [Nana-Miko/ChatLearning#56]
QQ版本：8.9.3
ChatLearning版本：3.0.1
电脑可以，手机无反应
控制台记录：

相似度计算引擎未找到相关问题(小于设定阈值0.5)
消耗用时: 0.11923 seconds
-----Cosmatch INFO End-----
已过滤，原因：与指令匹配 发送者xxxxxxxx 来自群xxxxxxxx

**Comment by Nana-Miko** [comment]
这个不清楚是不是手机qq8.9的bug，在回复消息的时候，那个艾特自己看的见，但是别人是无法看见的。
可以用以下方法解决
1.直接发送!d 1删除
2.点完回复后再加一个艾特bot

**Comment by MMM2042** [comment]
明白了，感谢
