### ISSUE TITLE
回复消息的时候不支持表情包吗？

### ISSUE THREAD

**Issue by Natane0808** [Nana-Miko/ChatLearning#62]
![image](https://user-images.githubusercontent.com/48778330/192130225-f919c728-1b3a-4b0b-b4d0-210c031597d2.png)

**Comment by Nana-Miko** [comment]
这种可能是特殊表情，需要商城购买使用的那种

**Comment by Natane0808** [comment]
哦好的，还有一个问题，我上传两次不同人的的音源，是会覆盖掉第一次的音源吗

**Comment by Nana-Miko** [comment]
> 哦好的，还有一个问题，我上传两次不同人的的音源，是会覆盖掉第一次的音源吗

会的哦
