### ISSUE TITLE
Windows打开.exe后出现如下报错

### ISSUE THREAD

**Issue by XinFeng114514** [Nana-Miko/ChatLearning#63]
![QQ截图20221104094753](https://user-images.githubusercontent.com/117132950/199867773-9c5c2a19-196e-4a33-80cc-b59ae81a4f26.png)
也不知道是什么原因

**Comment by Nana-Miko** [comment]
系统版本是什么

**Comment by Nana-Miko** [comment]
尝试用管理员运行

**Comment by XinFeng114514** [comment]
Windows7系统
管理员运行也是一样的情况

**Comment by Nana-Miko** [comment]
用源码运行吧，新版本的python不支持32位

**Comment by XinFeng114514** [comment]
我是64位的系统

**Comment by Nana-Miko** [comment]
> 我是64位的系统

试试用源码包运行?之前也有win7系统不成功的案例

**Comment by XinFeng114514** [comment]
我试试吧
