### ISSUE TITLE
运行一段时间后重启时闪退

### ISSUE THREAD

**Issue by ariaxo** [Nana-Miko/ChatLearning#68]
拖进cmd里的报错：

> C:\Users\thuli>"C:\Users\thuli\Downloads\ChatLearning Windows\Windows\ChatLearning.exe"
> Traceback (most recent call last):
>   File "Chatmain.py", line 29, in <module>
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "ChatReply.py", line 10, in <module>
>   File "jieba\__init__.py", line 513, in set_dictionary
> Exception: jieba: file does not exist: C:\Users\thuli\dict.txt
> [13536] Failed to execute script 'Chatmain' due to unhandled exception!

尝试覆盖config.clc，无果，报错相同

**Comment by Nana-Miko** [comment]
相关0kb错误在3.0.3版本将会修复

**Comment by ariaxo** [comment]
> 相关0kb错误在3.0.3版本将会修复

更新后错误仍存在...
并发现原因是端口设置为8080的问题。但是用8080之外的端口无法与api取得联系（api端口也一并换过了

**Comment by ariaxo** [comment]
> > 相关0kb错误在3.0.3版本将会修复
> 
> 更新后错误仍存在... 并发现原因是端口设置为8080的问题。但是用8080之外的端口无法与api取得联系（api端口也一并换过了

补充：
setting.yml

> singlemode: false
>   http:
>     host: 0.0.0.0
>     port: 8080
>     cors: ["*"]

data.json

>   http:
>     host: 0.0.0.0
>     port: 8080
>     cors: ["*"]
