### ISSUE TITLE
【汇总】近期的优化目标和讨论

### ISSUE THREAD

**Issue by FuYon** [Nana-Miko/ChatLearning#7]

**Comment by Nana-Miko** [comment]
感谢你的建议，后续将会整合一个较全的近期todo
转发模式是指qq中那个多选转发消息吗

**Comment by FuYon** [comment]
> 感谢你的建议，后续将会整合一个较全的近期todo 转发模式是指qq中那个多选转发消息吗

是的，可以用于折叠消息，具体可以看看[色图插件](https://github.com/cssxsh/pixiv-helper/)的应用

**Comment by FuYon** [comment]
![image](https://user-images.githubusercontent.com/57851695/155286151-23586160-7fe3-4aa9-ac4c-3f8ed5cf4910.png)

甚至还可以随机转发消息里面的人为任意群的任意群友

**Comment by FuYon** [comment]
![image](https://user-images.githubusercontent.com/57851695/155286573-e3d7cd31-e372-44db-b016-5b18f04d2b96.png)
人名也是可改的

**Comment by Nana-Miko** [comment]
我有点没搞懂，折叠消息需要用在什么方面上呢？

**Comment by FuYon** [comment]
一般用在查询的消息繁琐且多的时候，也可以不用，全都塞到一个消息里面。塞不下才会这样用，可以减少bot发言频率被风控或者封号。

**Comment by FuYon** [comment]
还有这种离谱的符号语言怎么过滤![Screenshot_20220223-175055_TIM.png](https://user-images.githubusercontent.com/57851695/155295813-f1df80d8-f6a5-40a7-9a82-e8cfdd2075ae.png)
