### ISSUE TITLE
无法上传音源

### ISSUE THREAD

**Issue by Kabisang** [Nana-Miko/ChatLearning#75]
输入uploadwav之后 就闪退了
是不是环境的问题呀
![image](https://user-images.githubusercontent.com/94161903/222442331-21b401d3-afd6-436c-ba9d-880a3117abaf.png)

**Comment by Nana-Miko** [comment]
音源的问题，尝试用格式工厂转成wav

**Comment by Kabisang** [comment]
> 

可以了！谢谢您！我在本地倒是可以了 云端服务器尝试打开wav文件时会弹出个没有注册类 没搞懂是怎么回事

**Comment by Kabisang** [comment]
> 音源的问题，尝试用格式工厂转成wav
现在上传音源服务器未响应！

**Comment by Nana-Miko** [comment]
见帖子最新回复
服务器到期了，转语音停止服务了）
