### ISSUE TITLE
如果直接使用release压缩包内文件进行覆盖，会导致群配置文件丢失

### ISSUE THREAD

**Issue by fatinghenji** [Nana-Miko/ChatLearning#8]
RT
使用新包解压后直接覆盖原文件夹内容，会导致learning和reply记录的群号丢失

**Comment by FuYon** [comment]
无可厚非，多试一下覆盖部分文件，多试几次可能才能找到不丢失的情况

**Comment by Nana-Miko** [comment]
下次更新我会好好写上说明本次更新需要覆盖哪些文件，全部覆盖导致learning和reply记录的群号丢失是不可避免的
