### ISSUE TITLE
服务器是挂了吗？访问不到

### ISSUE THREAD

**Issue by kuronekonano** [Nana-Miko/ChatLearning#80]
http://124.222.165.166:19630 这个地址貌似并不能访问到，看源码的时候发现几个问题：
1. check 的时候会请求以上地址做update ，但是有一个 try except 却返回了个 None , 导致 None 是没有 index 的，后续判断直接报错，没发进入【无法连接服务器】的 else 分支，我手动改成了 return (0, xxxxx)
2. 以及在 macos 上跑会出错，原因是 main.py 里只做了 elif system==Linux ，注释掉改成 else 就好了

**Comment by kuronekonano** [comment]
我觉得我可以提一些 pr （

**Comment by Nana-Miko** [comment]
1.服务器的话因为过期了，然后资金原因就没继续运行了
2.当时没想到macos）
其实是我这段时间抽不出空来发布release，就是两行代码的事
如果愿意看我屎山代码的话我也是特别欢迎提pr的）
