### ISSUE TITLE
使用源码部署时遇到的一点小问题

### ISSUE THREAD

**Issue by qingshanlanshan** [Nana-Miko/ChatLearning#83]
***系统是MacOS
1. 配置环境时，直接使用requirements.txt的话，qcloud_cos会报错说只适用于python2，需手动pip install -U cos-python-sdk-v5
2. dict.txt在源码中没找到，只能从release里打包的文件中复制了一个
3. Chatmain里2152行附近，路径分隔符没有Mac系统的对应if分支，或许可以用os.sep代替ifelse
4. 使用check功能时，若未连接到服务器，checkversion()会返回None，导致ChatCheck.py第169行附近的分支出错。应该先判断None再判断返回值吧

上面是一点小问题，下面是个人疑问

如果我想重新部署的话，能否把以前的Merge.cl文件，放到WordStock目录下直接使用？
在自己测试的时候（admin和bot两个人的群），发送的消息都被过滤了（“与过滤字典中消息类型匹配”），想问下这个过滤规则是什么样的？

感谢

**Comment by Nana-Miko** [comment]
了解 我当时确实把mac给忘了
以前的文件是可以用的
如果是消息类型被过滤，就是一些默认过滤的消息类型，可以在filter.clc文件里面的type处看见

**Comment by qingshanlanshan** [comment]
好的谢谢mua

**Comment by qingshanlanshan** [comment]
> 了解 我当时确实把mac给忘了 以前的文件是可以用的 如果是消息类型被过滤，就是一些默认过滤的消息类型，可以在filter.clc文件里面的type处看见

在linux上用miniconda试了下，requirements.txt也是不能直接用。另外，jiepai和numpy需要额外下载。jieba在mac上其实也是要自己装的之前忘了说了。

在启动的时候，有以下报错：
/root/ChatLearning/./Chatmain.py:2224: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
不过应该不影响使用
