### ISSUE TITLE
!uploadwav 上传失败,服务器未响应

### ISSUE THREAD

**Issue by CBEpt** [Nana-Miko/ChatLearning#84]
![1P 9{JII1SKX4G6`(Y~ ` G](https://user-images.githubusercontent.com/103420806/228859548-cf5a81f6-c722-49ce-a408-cafea33f949b.png)
请问现在服务器状态是如何？有无交流群？感谢！

**Comment by MC57348** [comment]
服务器已经关了
![image](https://github.com/Nana-Miko/ChatLearning/assets/52664742/2ccde6a7-2d2b-4d1f-b053-58b0ef480e97)
