### ISSUE TITLE
[Feature Request] 让bot连续回复！

### ISSUE THREAD

**Issue by FuYon** [Nana-Miko/ChatLearning#9]
## 超级~
这只是一个有待讨论的特性，能够大大的提高bot的智商（从某种层面上）

目前的学习逻辑是按顺序记录“2”句话作为问和答。
## “2~∞”
可以确定的是，“2”这个数字有极大的发展潜力。把2随机扩展到3、4、5，会发生什么？
## 挑战
- 发送＞1条的消息时，延时一定要有，不然频繁发送容易封号。

- 试试才知道
## 起因
- 发现bot经常说话只说一半；
- 如果bot可以连续说话的话，拟人性和趣味性会得到质的飞跃，尤其是在基于大量数据的基础上。
- 总结一下
优点不用说，这个特性很有价值。
不过一定也会面临相应的问题，但是不试试怎么知道这问题到底多有趣呢？又能从中学到什么呢~

**Comment by Nana-Miko** [comment]
这个要实现其实还是很简单的，因为在记录词库的时候为每个问和答配备了time属性

**Comment by FuYon** [comment]
可，可以设置概率，有时候收记录多条消息作为回答让bot延时连续发送（建议2~5秒，随机数也可），有时候只记录一个答案。

**Comment by Nana-Miko** [comment]
> 

这个可以有，当有多个答案的时候bot会几率回复多条答案

**Comment by FuYon** [comment]
但回复多条答案是整合过的，和按顺序记录多条答案是不同的。
当概率到某个问题收集多条消息时，在控制台它看起来是这样的：
（时间顺序）
- 问
友人1：Nana_miko我爱你！
- 答
友人2：！！！终于表白了！
友人3：天啊
友人4：omg，快点截屏保存 ~
友人5：太甜了ᐠ( ᐢ ᵕ ᐢ )ᐟ

触发时bot回复：
！！！终于表白了！
（延时2s~5s）
天啊
（延时2s~5s）
omg，快点截图保存 ~
（延时2s~5s）
太甜了

**Comment by Nana-Miko** [comment]
我的已经开了大概3-4天了，目前有2w2条答案，当然应该是我在三个经常99+的群开了记录的原因

**Comment by Nana-Miko** [comment]
![IMG_20220223_234423](https://user-images.githubusercontent.com/46672817/155354769-c4cccc11-346d-4b55-8d64-657fb19a36a7.png)
总共2w2

**Comment by FuYon** [comment]
好家伙，这得用转发消息吧，不然容易风控或者封号；或者合并成一条

**Comment by Nana-Miko** [comment]
> 

收到，正在修改相关代码

**Comment by FuYon** [comment]
早点睡，我弄一会博客hh

**Comment by Nana-Miko** [comment]
新版本正在打包，马上发布

**Comment by FuYon** [comment]
晚安~

**Comment by FuYon** [comment]
我去洗个澡再pull一遍

**Comment by Nana-Miko** [comment]
久等啦）新版本已经发布了

**Comment by FuYon** [comment]
睡觉睡觉，辛苦啦！
